# src/ads_agent/agents/writer/nodes.py
"""
Writer Agent node — Phase 1 stub.

In Phase 1: returns a minimal DecisionReport from stubs.
In Phase 4: replaced with full structured report generation.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import TYPE_CHECKING

from langchain_core.messages import AIMessage
import structlog

from ads_agent.agents.common import safe_node
from ads_agent.core.entities.decision_report import DecisionReport, RecommendationStrength
from ads_agent.core.entities.execution_receipt import AgentMetrics, AgentStatus

if TYPE_CHECKING:
    from ads_agent.agents.state import AgentState

log = structlog.get_logger(__name__)


@safe_node("writer")
def writer_node(state: AgentState) -> dict:
    """
    Writer Agent: produces the final structured Decision Report.

    Phase 1: assembles a stub report from stub data.
    """
    log.info("writer_node_started", request_id=state["request"].id)

    started_at = datetime.now(UTC)

    # Build a minimal stub report that satisfies the DecisionReport schema
    report = DecisionReport(
        request_id=state["request"].id,
        query=state["request"].query,
        recommendation=(
            "[STUB] Recommendation will be generated by LLM in Phase 4. "
            "This placeholder confirms the writer node executed successfully."
        ),
        recommendation_strength=RecommendationStrength.INCONCLUSIVE,
        summary=(
            "This is a stub summary. The full analysis pipeline will produce "
            "a detailed, evidence-backed report in Phase 4."
        ),
        trade_offs=[],
        key_considerations=["Phase 1 stub — no real analysis performed"],
        sources=[],
    )

    completed_at = datetime.now(UTC)

    metrics = AgentMetrics(
        agent_name="writer",
        status=AgentStatus.COMPLETED,
        started_at=started_at,
        completed_at=completed_at,
    )

    receipt = state.get("receipt")
    if receipt:
        receipt.add_agent_metrics(metrics)

    log.info("writer_node_completed", duration_s=metrics.duration_seconds)

    return {
        "final_report": report,
        "messages": [AIMessage(content=report.recommendation, name="writer")],
        "receipt": receipt,
    }
